name: Check
on:
  pull_request:
    branches: [main]
  workflow_call:
  workflow_dispatch:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: { node-version: "16", cache: "yarn" }
      - name: Install Yarn packages
        run: yarn install --frozen-lockfile
      - name: Check prettier
        run: |
          yarn run prettier
          CODE=$?
          if [ "$CODE" != "0"  ]; then exit 1; fi

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: { node-version: "16", cache: "yarn" }
      - name: Install Yarn packages
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn run build

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: { node-version: "16", cache: "yarn" }
      - name: Install Yarn packages
        run: yarn install --frozen-lockfile
      - name: Check tests
        run: yarn run test

  cicd-authorisation:
    defaults:
      run:
        working-directory: cicd-authorisation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: { cache: "npm" }
      - name: Install NPM packages
        run: npm ci
      - name: Check tests
        run: npm run test
